### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Abd659** [zer0dx/cryptondie#1]
The error:
Traceback (most recent call last):
  File "cryptondie.py", line 75, in <module>
    main()
  File "cryptondie.py", line 54, in main
    info.log("Postal: {0}".format(public_info["postal"]))
KeyError: 'postal'

**Comment by zer0dx** [comment]
Hi,

Whats your python version?

**Comment by Abd659** [comment]
Python 3.7.4+

**Comment by changtraisitinh** [comment]
i have a error 
```
root@kali:~/Tools/cryptondie# python3 cryptondie.py --web-service http://127.0.0.1:5000 --dir /var/www/ --key 123456789 --encrypt --verbose

Traceback (most recent call last):
  File "cryptondie.py", line 71, in <module>
    main()
  File "cryptondie.py", line 48, in main
    infos.send_infos(web_service, key)
  File "/root/Tools/cryptondie/modules/create_infos.py", line 34, in send_infos
    'target_postal': public_info["postal"],
KeyError: 'postal'
```
